{{- $chartName := include "nodejs-web-app.name" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-web-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ $chartName }}
    app.kubernetes.io/instance: {{ $releaseName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $chartName }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/component: {{ .Values.activeColor | default "blue" }}
