apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-web-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nodejs-web-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nodejs-web-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
